# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 01:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('period', models.CharField(max_length=3)),
                ('prof', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=7)),
                ('priv', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyBuddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', django.contrib.postgres.fields.jsonb.JSONField()),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Class')),
            ],
        ),
        migrations.CreateModel(
            name='UserBuddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddies', models.ManyToManyField(to='website.StudyBuddy')),
                ('classes', models.ManyToManyField(to='website.Class')),
                ('groups', models.ManyToManyField(to='website.Groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studybuddy',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='website.UserBuddy'),
        ),
        migrations.AddField(
            model_name='studybuddy',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='website.UserBuddy'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserBuddy'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Groups'),
        ),
        migrations.AddField(
            model_name='class',
            name='groups',
            field=models.ManyToManyField(to='website.Groups'),
        ),
    ]
