# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='groups',
            field=models.ManyToManyField(blank=True, to='website.Groups'),
        ),
        migrations.AlterField(
            model_name='studybuddy',
            name='times',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='studybuddy',
            name='user2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='website.UserBuddy'),
        ),
        migrations.AlterField(
            model_name='userbuddy',
            name='buddies',
            field=models.ManyToManyField(blank=True, to='website.StudyBuddy'),
        ),
    ]
