# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160930_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='class1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='thisclass', to='website.Class'),
            preserve_default=False,
        ),
    ]
