# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161001_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='website.Groups'),
        ),
    ]
